apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pf4v5dp7a-java-springboot 
  janus-idp.io/tekton: pf4v5dp7a-java-springboot
  backstage.io/kubernetes-id: pf4v5dp7a-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pf4v5dp7a-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml